spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm567373
spring.datasource.password=090198
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.application.name=banco
server.port=8080
